// gen-fog.js — writes fog.svg: a scatter of ~20 mostly-transparent gray blobs
// randomly placed over an area large enough to cover one quadrant tile. The fog
// reads as accumulated DENSITY of overlapping translucent blobs (not one solid
// mass), which also gives it a naturally ragged, organic edge. The whole cloud
// gently ROCKS via an embedded rotate so it animates inside an <img>.
//
// Coordinate space is DERIVED (see the geometry block below) so nothing ever
// touches the viewBox edge — no clipping. The scatter field covers the quadrant
// TILE plus a SPILL past every side (so neighboring fog tiles interleave), and
// a PAD margin larger than the max blob radius surrounds the whole field, so
// even an outermost blob's rim stays well inside the viewport.
// Run:  node gen-fog.js   (writes fog.svg next to this file)

const fs = require('fs');
const path = require('path');

// ---- knobs -------------------------------------------------------------------
const N = 200;             // number of blobs
const R_MIN = 13;          // blob radius range
const R_MAX = 20;
const OP_MIN = 0.14;       // per-blob opacity range (mostly transparent)
const OP_MAX = 0.30;
const COLORS = ['#4a4d53', '#565a60', '#3f4247', '#616570']; // grays, some lighter
const MIN_DIST = 5;        // reject a candidate whose center is within this of an
                           // already-placed blob's center (spaces the scatter out)
const MAX_TRIES = 60;      // resample attempts per blob before giving up (guards
                           // against an impossible-to-fill field looping forever)

// ---- geometry (derived) ------------------------------------------------------
const TILE = 50;           // the quadrant tile the fog must cover
const SPILL = 90;          // how far the scatter of centers extends past each tile edge
                           // (large, so the fog reaches into neighbors and banks blend)
const PAD = R_MAX + 2;     // transparent margin around the scatter field; > R_MAX so
                           // no blob's rim can reach the viewBox edge -> zero clipping
// scatter field for blob CENTERS: the tile grown by SPILL on every side
const FIELD = TILE + 2 * SPILL;
const SPAN_MIN = PAD;                 // centers live in [PAD, PAD+FIELD]
const SPAN_MAX = PAD + FIELD;
const SIZE = FIELD + 2 * PAD;         // full viewBox extent
const CENTER = SIZE / 2;              // rock pivot (viewBox center)
// -----------------------------------------------------------------------------

// simple seeded RNG so the scatter is reproducible (change SEED to reroll)
let seed = 20260717;
function rnd() { seed = (seed * 1103515245 + 12345) & 0x7fffffff; return seed / 0x7fffffff; }
const rangeR = (a, b) => a + (b - a) * rnd();
const pick = (arr) => arr[Math.floor(rnd() * arr.length)];

// Rejection sampling: keep a candidate only if its center is at least MIN_DIST
// from every already-placed center. This departs from pure randomness so the
// blobs spread more evenly instead of clumping. If a blob can't find a spot in
// MAX_TRIES, we place the last try anyway (so N is still met on a crowded field).
const blobs = [];
for (let i = 0; i < N; i++) {
  let cx, cy;
  for (let t = 0; t < MAX_TRIES; t++) {
    cx = rangeR(SPAN_MIN, SPAN_MAX);
    cy = rangeR(SPAN_MIN, SPAN_MAX);
    const tooClose = blobs.some(b => Math.hypot(cx - b._cx, cy - b._cy) < MIN_DIST);
    if (!tooClose) break;
  }
  blobs.push({
    _cx: cx, _cy: cy,                 // raw coords, for the distance test above
    cx: cx.toFixed(1),
    cy: cy.toFixed(1),
    r:  rangeR(R_MIN, R_MAX).toFixed(1),
    op: rangeR(OP_MIN, OP_MAX).toFixed(2),
    fill: pick(COLORS),
  });
}

const circles = blobs
  .map(b => `      <circle cx="${b.cx}" cy="${b.cy}" r="${b.r}" fill="${b.fill}" opacity="${b.op}"/>`)
  .join('\n');

const svg =
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SIZE} ${SIZE}" width="${SIZE}" height="${SIZE}">
  <!-- FOG cloud (generated by gen-fog.js). ~${N} mostly-transparent gray blobs
       scattered over the quadrant tile + spill, spaced by rejection sampling.
       The fog is the accumulated DENSITY of overlapping translucent blobs,
       giving a soft, ragged, organic edge with no straight sides. A PAD margin
       (> max blob radius) surrounds the field so NOTHING touches the viewBox
       edge — zero clipping. Gently ROCKS via an embedded rotate (self-contained).
       NOTE: this standalone file is a reference/preview; in-game the fog is built
       fresh per placement by makeFog() in ui.js so no two tiles are identical. -->
  <title>Fog — unknown</title>
  <g>
    <animateTransform attributeName="transform" type="rotate"
      dur="7s" repeatCount="indefinite"
      values="-1.5 ${CENTER} ${CENTER}; 1.5 ${CENTER} ${CENTER}; -1.5 ${CENTER} ${CENTER}"/>
${circles}
  </g>
</svg>
`;

fs.writeFileSync(path.join(__dirname, 'fog.svg'), svg);
console.log(`wrote fog.svg — ${N} blobs`);
